name: music_kit
description: A Flutter plugin to access and play Apple Music.
version: 1.1.0
homepage: https://github.com/misiio/flutter_music_kit/tree/master/music_kit

publish_to: none

environment:
    sdk: ">=2.18.2 <3.0.0"
    flutter: ">=2.5.0"

dependencies:
    flutter:
        sdk: flutter
    # music_kit_platform_interface: ^1.1.0
    music_kit_platform_interface:
        git:
            url: https://github.com/HondaYt/flutter_music_kit.git
            path: music_kit_platform_interface

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    plugin:
        platforms:
            android:
                package: app.misi.music_kit
                pluginClass: MusicKitPlugin
            ios:
                pluginClass: MusicKitPlugin
